services:
  - type: web
    name: president-backend
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    autoDeployTrigger: commit
