services:
  - type: web
    name: president-backend-api
    runtime: node
    plan: free
    region: singapore
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    autoDeployTrigger: commit
